name: Build Appliance Installer

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the main branch
        uses: actions/checkout@v3

      - name: Capture build date into release
        run: |
          mkdir build
          echo date >> release/release.txt
          cat release/release.txt

      - name: Tar files
        run: tar -cvf release.tar release/

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: release
          path: release.tar      
      
      #- name: Display Runtime Env
      #  run: |
      #    whoami
      #    pwd
      #    terraform -v
      #    ls -la