name: Build Appliance Installer

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the main branch
        uses: actions/checkout@v2

      - name: echo date >> date.txt
        run: |
          mkdir build
          echo date >> build/build.txt
          cat build/build.txt

      - name: Tar files
        run: tar -cvf build.tar build/
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build.tar      
      
      #- name: Display Runtime Env
      #  run: |
      #    whoami
      #    pwd
      #    terraform -v
      #    ls -la