name: Build Appliance Installer

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Display Runtime Env
        run: |
          whoami
          pwd
          terraform -v
          ls -la
     
      - name: Build Appliance Installer
        run: |
          sh build/build.sh -v '5.2.2'